/**
 * The State root as plain JSON, and back.
 *
 * Everything in the root is already a JSON value except the generator, which is a small
 * object behind a class. So this is the whole of the round trip, and it is lossless — unlike
 * the projection in `./project.ts`, which is upstream's save schema and drops what upstream
 * rebuilds at load.
 *
 * It exists for the fixture a divergence writes out: the failing step's *input* state,
 * complete on its own because the generator lives in it, so the step replays
 * without Python and without running the Scenario from the beginning.
 */

import { Rng, type RngState } from "./rng/random.ts";
import type { SimulationState } from "./state.ts";

export type PlainState = Omit<SimulationState, "rng"> & { readonly rng: RngState };

export function toPlain(state: SimulationState): PlainState {
  return { ...state, rng: state.rng.toState() };
}

/**
 * The inverse. The cast is the one place the port trusts a document it did not just write:
 * a fixture is generated by the harness and lives beside the tests, so validating it would
 * only move the failure from a wrong answer to a wrong answer with a schema attached.
 */
export function fromPlain(plain: PlainState): SimulationState {
  return { ...plain, rng: Rng.fromState(plain.rng) } as SimulationState;
}
