// boundary-intent harness: a test, so it decides what to drive and what to expect
import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

import {
  MAX_LOG_ENTRIES,
  Rng,
  SaveContentError,
  appendLog,
  createInitialState,
  internalId,
  projectPersistent,
  restorePersistent,
  type LogEntry,
  type SavedObject,
  type SimulationState,
} from "../src/index.ts";
import { logRingVectors, logRingVectorsPath, staleFixture } from "./support/fixtures.ts";
import { logRingVectorsCheck, oracleAvailable, oracleRequired } from "./support/oracle.ts";

/**
 * The trace seam, on a rule no committed Scenario is long enough to reach: **the player log
 * is a bounded ring.** Upstream makes it `collections.deque(maxlen=1000)`
 * (`player.py:112`), so a game past a thousand entries silently drops its oldest — and the
 * cap is observable, because `serialize_obj` writes the deque out whole and
 * `deserialize_obj` reads a saved log back through the same bound.
 *
 * The Oracle answers here off the reference rather than out of a Trace: the two committed
 * Scenarios that reach a log entry produce two between them, and the long generated
 * Scenario that would reach the cap is not written yet. Every expectation below comes from
 * sim/test/fixtures/reference-log-ring.json, generated by tools/oracle/log_ring.py, and the
 * `--check` at the foot of this file is what keeps the fixture honest against a bump.
 *
 * # Which half each test pins
 *
 * The ring has two sides, and only one of them was ever wrong. The first three tests cover the
 * *append* side — `appendLog` and `projectPersistent` — and are regression guards that pin the
 * rule against the reference rather than against a hard-coded 1000. The *load* side is
 * pinned only by the tests below that drive `restorePersistent`: reverse-apply any part of
 * `restoreLog`'s truncation and one of those goes red, while the first three stay green. So do
 * not read a green run of the first three as the load path being covered.
 */

const cap = logRingVectors.maxEntries;

/** `cap + 1` entries, emitted one game-second apart from 0, so the oldest survivor is 1. */
function pastTheCap(): readonly LogEntry[] {
  return Array.from({ length: logRingVectors.appendedPastTheCap.offered }, (_, rawEmitTime) => ({
    kind: "event-emitted",
    rawEmitTime,
    fields: { event_id: logRingVectors.eventId },
  }));
}

/** The ends a log covers, in the fixture's own shape. */
function span(entries: readonly { readonly rawEmitTime: number }[]) {
  return {
    entries: entries.length,
    oldestRawEmitTime: entries[0]?.rawEmitTime ?? null,
    newestRawEmitTime: entries.at(-1)?.rawEmitTime ?? null,
  };
}

function savedSpan(saved: readonly SavedObject[]) {
  return span(saved.map((entry) => ({ rawEmitTime: entry.raw_emit_time as number })));
}

function savedLog(state: SavedObject): readonly SavedObject[] {
  return (state.player as SavedObject).log as readonly SavedObject[];
}

const newGame = { seed: 1, difficulty: "normal" } as const;

/** A readable Save of a fresh game, with `log` replaced by the entries handed in. */
function saveCarrying(entries: readonly LogEntry[]): SavedObject {
  const state = projectPersistent(createInitialState(newGame));
  const player = state.player as SavedObject;
  return {
    ...state,
    player: {
      ...player,
      log: entries.map((entry) => ({
        log_id: entry.kind,
        raw_emit_time: entry.rawEmitTime,
        event_id: internalId("event", String(entry.fields.event_id)),
      })),
    },
  };
}

function load(saved: SavedObject): SimulationState {
  return restorePersistent(saved, Rng.seeded(1), { startDay: 0 });
}

describe("the player log", () => {
  it("is bounded where the reference bounds it", () => {
    expect(MAX_LOG_ENTRIES).toBe(cap);
  });

  it("drops the oldest entry once a game has produced more than the ring holds", () => {
    const log = appendLog([], pastTheCap());

    expect(span(log)).toEqual({
      entries: logRingVectors.appendedPastTheCap.entries,
      oldestRawEmitTime: logRingVectors.appendedPastTheCap.oldestRawEmitTime,
      newestRawEmitTime: logRingVectors.appendedPastTheCap.newestRawEmitTime,
    });
  });

  it("writes the ring the reference writes, not the entries it was offered", () => {
    const state = createInitialState(newGame);
    const driven: SimulationState = { ...state, log: appendLog(state.log, pastTheCap()) };

    expect(savedSpan(savedLog(projectPersistent(driven)))).toEqual(logRingVectors.serialised);
  });

  /**
   * The other half of the same bound, and the one a Save can carry into the port from
   * outside: `Player.deserialize_obj` clears the deque and extends it (`player.py:689`), so
   * a saved log longer than the cap arrives truncated to its newest entries.
   */
  it("keeps only the newest entries when a Save carries more than the ring holds", () => {
    const restored = load(saveCarrying(pastTheCap()));

    expect(span(restored.log)).toEqual({
      entries: logRingVectors.restoredPastTheCap.entries,
      oldestRawEmitTime: logRingVectors.restoredPastTheCap.oldestRawEmitTime,
      newestRawEmitTime: logRingVectors.restoredPastTheCap.newestRawEmitTime,
    });
  });

  it("writes back what it read, so a Save cannot grow past the ring by round-tripping", () => {
    const restored = load(saveCarrying(pastTheCap()));

    expect(savedSpan(savedLog(projectPersistent(restored)))).toEqual(logRingVectors.serialised);
  });

  /**
   * The refusal path across the same truncation. `restoreLog` walks what the ring kept, but a
   * `SaveContentError` names a position in the document on disk, so the entries the ring
   * dropped still have to count in it. Only a Save past the cap can tell the two apart, and
   * a path off by the number dropped points a reader at the wrong entry of the file in front
   * of them.
   */
  it("names a refused entry by where it sits in the Save, not in what survived the ring", () => {
    const save = saveCarrying(pastTheCap());
    const log = [...savedLog(save)];
    const inTheSave = log.length - 1;
    log[inTheSave] = { ...(log[inTheSave] as SavedObject), log_id: "no-such-log-kind" };
    const damaged = { ...save, player: { ...(save.player as SavedObject), log } };

    expect(() => load(damaged)).toThrow(SaveContentError);
    expect(() => load(damaged)).toThrow(
      `state.player.log[${inTheSave}].log_id: no such log kind: no-such-log-kind`,
    );
  });
});

// Driving the Oracle needs the Python environment in `.venv`. A working copy without one skips these rather than
// failing on setup it does not have; CI sets SINGULARITY_ORACLE_REQUIRED, so there the
// absence is a failure and the check cannot quietly stop running.
const describeOracle = describe.skipIf(!(oracleAvailable || oracleRequired));

describeOracle("the committed log-ring vectors against a reference run made now", () => {
  it("still say what the reference says", () => {
    const result = logRingVectorsCheck();

    expect(result.stderr).toBe("");
    expect(result.status).toBe(0);
  });

  it("would name a cap that moved underneath them", () => {
    const stale = staleFixture(logRingVectorsPath, (document) => {
      document.maxEntries = cap + 1;
    });

    const result = logRingVectorsCheck(stale);

    expect(result.status).toBe(1);
    expect(result.stderr).toContain("maxEntries");
    expect(result.stderr).toContain("tools/oracle/log_ring.py");
  });

  it("leaves the committed fixture alone while checking it", () => {
    const before = readFileSync(logRingVectorsPath, "utf8");

    expect(logRingVectorsCheck().status).toBe(0);

    expect(readFileSync(logRingVectorsPath, "utf8")).toBe(before);
  });
});
