import { readFileSync, readdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { describe, expect, it } from "vitest";

import {
  LAND_DOTS,
  LAND_DOT_COLUMNS,
  LAND_DOT_ROWS,
  LAND_PATH,
  LAND_RING_COUNT,
} from "../src/ui/map/land.ts";

/**
 * The committed assets and what says where they came from.
 *
 * The land path's provenance and tolerance, `NOTICE`'s blocks, and the two self-hosted subsets
 * are facts about files rather than about behaviour, and a fact that is only ever checked by
 * reading stops being true quietly. These are the same shape as `sim/`'s boundary rules: a
 * rule over the repository, applied by the suite.
 */

const APP = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const REPOSITORY = resolve(APP, "..");

const read = (path: string): string => readFileSync(resolve(REPOSITORY, path), "utf8");

describe("the land path", () => {
  // Natural Earth 110m by way of world-atlas, projected into the 0-100 grid and
  // simplified at tolerance 0.3. The graphic exists to match the Content's own positions.
  it("is generated by a committed script from the pinned Natural Earth build", () => {
    const generator = read("tools/assets/build_land_path.py");

    expect(generator).toContain('PACKAGE = "world-atlas"');
    expect(generator).toContain('VERSION = "2.0.2"');
    expect(generator).toContain("TOLERANCE = 0.3");
    expect(generator).toMatch(/INTEGRITY = "sha512-/);
  });

  it("says in the file itself that it is generated, and how", () => {
    const module = read("app/src/ui/map/land.ts");

    expect(module).toContain("**Generated. Do not edit.**");
    expect(module).toContain("tools/assets/build_land_path.py");
    expect(module).toContain("Natural Earth 1:110m land");
    expect(module).toContain("tolerance 0.3");
  });

  // `content/` may hold converter output and nothing else — CI re-runs the converter and
  // fails on a dirty tree, and that check is only meaningful while the directory holds
  // nothing that was generated some other way.
  it("is committed outside content/", () => {
    expect(
      readdirSync(resolve(REPOSITORY, "content")).filter((name) => !name.endsWith(".json")),
    ).toEqual([]);
    expect(() => read("app/src/ui/map/land.ts")).not.toThrow();
  });

  it("stays inside the grid the pins are placed in", () => {
    const numbers = [...LAND_PATH.matchAll(/[ML](-?[\d.]+) (-?[\d.]+)/g)];

    expect(numbers.length).toBeGreaterThan(500);
    for (const [, x, y] of numbers) {
      expect(Number(x)).toBeGreaterThanOrEqual(0);
      expect(Number(x)).toBeLessThanOrEqual(100);
      expect(Number(y)).toBeGreaterThanOrEqual(0);
      expect(Number(y)).toBeLessThanOrEqual(100);
    }
  });

  // An edge longer than half the map is a ring crossing the antimeridian the long way, and it
  // draws as a sliver across the whole map. Only the pole's own edge may be that long.
  it("crosses the map only along a pole", () => {
    for (const ring of LAND_PATH.split("Z").filter(Boolean)) {
      const points = [...ring.matchAll(/[ML](-?[\d.]+) (-?[\d.]+)/g)].map(([, x, y]) => [
        Number(x),
        Number(y),
      ]);
      points.forEach(([x, y], index) => {
        const [nextX, nextY] = points[(index + 1) % points.length] as number[];
        if (Math.abs((x as number) - (nextX as number)) > 50) {
          expect([0, 100]).toContain(y);
          expect(nextY).toBe(y);
        }
      });
    }
  });

  // The dot matrix decides each cell whole, so a dot is land or sea and never half of each.
  it("carries a dot matrix of whole cells, land where the land is", () => {
    const land = (column: number, row: number): boolean =>
      ((BigInt(`0x${LAND_DOTS[row]}`) >> BigInt(LAND_DOT_COLUMNS - 1 - column)) & 1n) === 1n;

    expect(LAND_DOTS).toHaveLength(LAND_DOT_ROWS);
    for (const row of LAND_DOTS)
      expect(row).toMatch(new RegExp(`^[0-9a-f]{${LAND_DOT_COLUMNS / 4}}$`));
    // 20 degrees east on the equator is the Congo basin; 150 west is the open Pacific.
    expect(land(88, 40)).toBe(true);
    expect(land(13, 40)).toBe(false);
  });

  it("is one closed ring per island, and as many of them as it claims", () => {
    expect(LAND_PATH.match(/M/g)?.length).toBe(LAND_RING_COUNT);
    expect(LAND_PATH.match(/Z/g)?.length).toBe(LAND_RING_COUNT);
  });
});

describe("the two self-hosted font subsets", () => {
  const fontDir = resolve(APP, "src/ui/fonts");
  const files = readdirSync(fontDir);

  it("are exactly two woff2 files, each with its own licence sidecar", () => {
    const subsets = files.filter((name) => name.endsWith(".woff2"));

    expect(subsets).toHaveLength(2);
    for (const subset of subsets) {
      expect(files).toContain(`${subset}.license`);
      expect(read(`app/src/ui/fonts/${subset}.license`)).toContain("SIL Open Font License 1.1");
    }
    expect(files).toContain("LICENSE.OFL-1.1.txt");
  });

  it("are loaded from beside the stylesheet and from no CDN", () => {
    const stylesheet = read("app/src/ui/fonts/fonts.css");
    const sources = [...stylesheet.matchAll(/url\("([^"]+)"\)/g)].map(([, url]) => url as string);

    expect(sources).toHaveLength(2);
    for (const source of sources) {
      expect(source.startsWith("./")).toBe(true);
      expect(files).toContain(source.slice(2));
    }
    expect(stylesheet).not.toMatch(/https?:/);
  });

  // What the subsets do *not* carry, which is what a stylesheet may not claim they do. The
  // speed row's marks are U+25AE and U+25B6, outside every range either
  // `@font-face` declares, so the browser draws them from the fallback half of the stack and
  // never from the file. Read off the declaration rather than the file: `unicode-range` is
  // what decides which face is asked, whatever the face happens to contain.
  it("declare no range that reaches the speed row's marks", () => {
    const ranges = [
      ...read("app/src/ui/fonts/fonts.css").matchAll(/U\+([0-9A-F]+)(?:-([0-9A-F]+))?/g),
    ].map(([, from, to]) => [
      Number.parseInt(from as string, 16),
      Number.parseInt((to ?? from) as string, 16),
    ]);

    expect(ranges.length).toBeGreaterThan(20);
    for (const mark of ["▮", "▶"]) {
      const point = mark.codePointAt(0)!;
      expect(ranges.filter(([from, to]) => point >= from! && point <= to!)).toEqual([]);
    }
  });

  // Eight numbers sit side by side and must not shift, so tabular figures are load-bearing
  // rather than decorative — and the HUD's own four move every tick.
  it("are asked for with tabular figures wherever a value is shown", () => {
    for (const stylesheet of [
      "app/src/ui/Hud.css",
      "app/src/ui/ThreatBand.css",
      "app/src/ui/map/WorldMap.css",
    ]) {
      expect(read(stylesheet)).toContain("font-variant-numeric: tabular-nums");
    }
  });
});

describe("NOTICE", () => {
  const notice = read("NOTICE");

  it("carries the map data's provenance", () => {
    expect(notice).toContain("Natural Earth");
    expect(notice).toContain("world-atlas");
    expect(notice).toContain("app/src/ui/map/land.ts");
  });

  it("carries the fonts' provenance, both of them", () => {
    expect(notice).toContain("SIL Open Font License 1.1");
    expect(notice).toContain("Archivo");
    expect(notice).toContain("IBM Plex Mono");
  });

  // The fonts carry sidecars, so `NOTICE` may not say there are none.
  it("no longer says there are no sidecars", () => {
    expect(notice).not.toContain("there are none today");
    expect(notice).not.toContain("No artwork, fonts or audio are carried over.");
  });
});

describe("the accent pair", () => {
  // WCAG 2.x relative luminance and contrast ratio, over the literal hex values in
  // tokens.css — accent-filled controls carry normal-size text, so the pair must
  // measure at or above 4.5:1.
  const luminance = (hex: string): number =>
    [1, 3, 5]
      .map((start) => {
        const v = parseInt(hex.slice(start, start + 2), 16) / 255;
        return v <= 0.04045 ? v / 12.92 : ((v + 0.055) / 1.055) ** 2.4;
      })
      .reduce((sum, channel, i) => sum + channel * [0.2126, 0.7152, 0.0722][i]!, 0);

  it("measures at or above 4.5:1, ink on accent", () => {
    const tokens = read("app/src/ui/tokens.css");
    const token = (name: string): string => {
      const match = tokens.match(new RegExp(`${name}: (#[0-9a-f]{6});`));
      if (!match?.[1]) throw new Error(`${name} is not a plain hex token`);
      return match[1];
    };

    const accent = luminance(token("--colour-accent"));
    const ink = luminance(token("--colour-accent-ink"));
    const ratio = (Math.max(accent, ink) + 0.05) / (Math.min(accent, ink) + 0.05);

    expect(ratio).toBeGreaterThanOrEqual(4.5);
  });
});
